#version: 2.1

#orbs:
#  maven: circleci/maven@0.0.12

#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Start Selenium
          command: maven clean test
          background: true